-- return {
--   {
--     "williamboman/mason.nvim",
--     config = function()
--       require("mason").setup()
--     end
--   },
--   {
--     "williamboman/mason-lspconfig.nvim",
--     config = function()
--       require("mason-lspconfig").setup({
--         ensure_installed = {
--           "clangd",
--           "pylsp",
--           "lua_ls",
--           "texlab",
--         }
--       })
--     end
--   },
--   {
--     "neovim/nvim-lspconfig",
--     config = function()
--       local lspconfig = require("lspconfig")
--       lspconfig.clangd.setup({})
--       lspconfig.pylsp.setup({})
--       lspconfig.lua_ls.setup({})
--       lspconfig.texlab.setup({})
--     end
--   },
--   {
--     "nvim-telescope/telescope-ui-select.nvim",
--     config = function()
--       require("telescope").setup({
--         extensions = {
--           ["ui-select"] = {
--             require("telescope.themes").get_dropdown {
--             }
--           }
--         }
--       })
--       require("telescope").load_extension("ui-select")
--     end
--   },
-- }
